name: Run Selenium Tests in Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  selenium-tests:
    runs-on: self-hosted  # ← Bu artık çalışacak!

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Build Docker image
      run: docker build -t tdm-selenium-tests .

    - name: Create reports directory
      run: mkdir -p reports

    - name: Run Selenium Tests in Docker
      run: |
        docker run --rm -v ${{ github.workspace }}/reports:/app/reports \
          --env-file tdm_automation/Tests/.env \
          tdm-selenium-tests

    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-report
        path: reports/